---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tf-runner-rolebinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tf-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tf-runner-cr
rules:
- apiGroups:
  # - ""
  # - extensions
  # - apps
  # - networking.k8s.io
  - apiextensions.k8s.io
  resources:
  # - '*'
  - customresourcedefinitions
  verbs:
  - 'list'
  - 'get'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tf-runner-crb
roleRef:
  kind: ClusterRole
  name: tf-runner-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: tf-runner
  namespace: dev
